# Generated by Django 3.0.7 on 2020-06-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='fullname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Points')),
            ],
            options={
                'verbose_name': 'leaderboard',
                'verbose_name_plural': 'leaderboards',
            },
        ),
    ]
